pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                dir('Ex 2/code/mlops-ci') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Ex 2/code/mlops-ci') {
                    sh 'mvn test'
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying application...'
            }
        }
    }
}
